In [ ]:
import numpy as np

In [12]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[6, 10, 40], [72, 27, 57]])
X

array([[ 6, 10, 40],
       [72, 27, 57]])

In [13]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [14]:
X.size

6

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([ 6, 72])

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([72, 27, 57])

In [18]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [20]:
X_pt = torch.tensor([[6, 10, 40], [72, 27, 57]])
X_pt

tensor([[ 6, 10, 40],
        [72, 27, 57]])

In [21]:
X_pt.shape

torch.Size([2, 3])

In [22]:
X_pt[1,:]

tensor([72, 27, 57])

In [23]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [24]:
X_tf = tf.Variable([[6, 10, 40], [72, 27, 57]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 6, 10, 40],
       [72, 27, 57]], dtype=int32)>

In [25]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [26]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [27]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([72, 27, 57], dtype=int32)>