In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([72, 2, 7])
x

array([72,  2,  7])

In [3]:
# hitung panjang vector x
len(x)

3

In [4]:
# tampilkan ukuran vector x
x.shape

(3,)

In [5]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(72)

In [7]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [8]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([72,  2,  7])

In [9]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [11]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([72,  2,  7])

In [12]:
# tampilkan ukuran dari vector x_t
y_t.shape

(3,)

In [14]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [16]:
x_pt = torch.tensor([72, 2, 7])
x_pt

tensor([72,  2,  7])

In [17]:
x_tf = tf.Variable([72, 2, 7])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([72,  2,  7], dtype=int32)>